import React from 'react';
import Head from 'next/head'

function MyHead() {
    return (
        <div>
            <Head>
                <title>Cageof</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>);
}

export default MyHead;
