import React from 'react'
import Head from 'next/head'

function MyHead(props) {
    return (
        <div>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.png" />
            </Head>
        </div>);
}

export default MyHead
